return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    indent = {
      enable = true,
      disable = { "c", "cpp" }, -- Use cindent for C/C++ instead
    },
    ensure_installed = {
      "bash",
      "diff",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "markdown",
      "markdown_inline",
      "python",
      "go",
      "gosum",
      "gomod",
      "gowork",
      "gotmpl",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "xml",
      "yaml",
      "css",
      "git_config",
      "git_rebase",
      "gitcommit",
      "hlsl",
      "http",
      "hyprlang",
      "make",
      "mermaid",
      "ruby",
      "rust",
      "sql",
      "templ",
      "terraform",
      "tmux",
      "zig",
    },
  },
}
